### PR TITLE
Pyflakes and PEP8 compliance

### PR DESCRIPTION
**Pull request by embreinhardt**
cc @bcavagnolo

### CODE REVIEW

**Comment by bcavagnolo** [comment]
Great idea Erika. And much thanks. Can we do this after I get my pending pull request merged? This will save me a potentially painful rebase.

**Comment by embreinhardt** [comment]
for sure

**Comment by bcavagnolo** [comment]
Hey @embreinhardt I rebased and push forced to migrate to the preferred license. This broke your PR. But I did clean up the flakes and add a flake8 build step. We cool?

**Comment by embreinhardt** [comment]
:+1:

**Pull request closed without merging**
